model:
  type: 'CascadeRCNNResNet50'

dataset:
  train: 'COCO'
  eval: 'COCO'
  n_fg_class: 80

solver:
  base_lr: 0.005  # 0.02 / 2
  n_iteration: 4000
  lr_step: [2000, 3000]
  hooks: ['WeightDecay', 'GradientClipping']

min_size: 600
max_size: 1000
n_gpu: 2
n_sample_per_gpu: 2
n_worker: 2
debug: true